# Generated by Django 3.0.8 on 2020-07-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(blank=True, db_column='nombreCategoria', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombrecliente', models.CharField(blank=True, db_column='nombreCliente', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('pais', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('codigopostal', models.IntegerField(blank=True, db_column='codigoPostal', null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('clientecol', models.CharField(blank=True, db_column='Clientecol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.IntegerField(db_column='idDespacho', primary_key=True, serialize=False)),
                ('nombrecompania', models.CharField(blank=True, db_column='nombreCompania', max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallesorden',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto')),
                ('idorden', models.IntegerField(db_column='idOrden', primary_key=True, serialize=False)),
                ('preciounidad', models.IntegerField(blank=True, db_column='precioUnidad', null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detallesorden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('idordenes', models.IntegerField(db_column='idOrdenes', primary_key=True, serialize=False)),
                ('fechasolicitud', models.DateTimeField(db_column='fechaSolicitud')),
                ('fechaenvio', models.DateTimeField(db_column='fechaEnvio')),
                ('medioenvio', models.CharField(blank=True, db_column='MedioEnvio', max_length=45, null=True)),
                ('direccionenvio', models.CharField(blank=True, db_column='direccionEnvio', max_length=45, null=True)),
                ('ciudadenvio', models.CharField(blank=True, db_column='ciudadEnvio', max_length=45, null=True)),
                ('regionenvio', models.CharField(blank=True, db_column='regionEnvio', max_length=45, null=True)),
                ('paisenvio', models.CharField(blank=True, db_column='paisEnvio', max_length=45, null=True)),
                ('codigopostal', models.IntegerField(blank=True, db_column='codigoPostal', null=True)),
                ('idcliente', models.CharField(db_column='idCliente', max_length=45)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, db_column='nombreProducto', max_length=45, null=True)),
                ('idproveedor', models.IntegerField(blank=True, db_column='idProveedor', null=True)),
                ('idcategoria', models.IntegerField(blank=True, db_column='idCategoria', null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('preciounitario', models.IntegerField(blank=True, db_column='precioUnitario', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.IntegerField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombrecompania', models.CharField(blank=True, db_column='nombreCompania', max_length=45, null=True)),
                ('nombrecontacto', models.CharField(blank=True, db_column='nombreContacto', max_length=45, null=True)),
                ('cargocontacto', models.CharField(blank=True, db_column='cargoContacto', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('codigopostal', models.IntegerField(blank=True, db_column='codigoPostal', null=True)),
                ('pais', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('sitioweb', models.CharField(blank=True, db_column='sitioWeb', max_length=45, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
